project:
  type: website
  output-dir: .

website:
  title: "duckreg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ibis.qmd
        text: Ibis
      - href: compression.qmd
        text: Compression
      - href: linear.qmd
        text: Linear
      - href: panel.qmd
        text: Panel
      - href: bitpacked-mundlak.qmd
        text: Bitpacked Panels
      - href: dml.qmd
        text: DML
      - href: glm.qmd
        text: GLMs
      - href: fisher-scoring.qmd
        text: Fisher Scoring
      - href: ridge.qmd
        text: Ridge
      - href: inference.qmd
        text: Inference
      - href: examples.qmd
        text: Examples
      - href: performance.qmd
        text: Performance
  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - ibis.qmd
      - compression.qmd
      - linear.qmd
      - panel.qmd
      - bitpacked-mundlak.qmd
      - dml.qmd
      - glm.qmd
      - fisher-scoring.qmd
      - ridge.qmd
      - inference.qmd
      - examples.qmd
      - performance.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    embed-resources: true
    page-layout: full

execute:
  echo: true
  eval: false
  warning: false
  message: false
  freeze: false
